apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstack
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      bb: bookstack
  template:
    metadata:
      labels:
        bb: bookstack
    spec:
      containers:
        - name: bookstack
          image: lscr.io/linuxserver/bookstack:latest
          imagePullPolicy: IfNotPresent
          env:
          - name: TZ
            value: "Etc/UTC"
          - name: APP_URL
            value: "http://bookstack.17042021.xyz"
          - name: APP_KEY
            value: "base64:kNq+ZVHRkOjR0KYbXjrsNpmScUfhtxBY7TAi/SQI3iY="
          - name: DB_HOST
            value: "bookstack-mysql-svc"
          - name: DB_PORT
            value: "3306"
          - name: DB_USERNAME
            value: "bookstack"
          - name: DB_PASSWORD
            value: "uglySEA62"
          - name: DB_DATABASE
            value: "bookstack"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      bb: mysql
  template:
    metadata:
      labels:
        bb: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5.6
          imagePullPolicy: IfNotPresent
          env:
          - name: MYSQL_ROOT_PASSWORD
            value: "uglySEA62"
          - name: MYSQL_DATABASE
            value: "bookstack"
          - name: MYSQL_USER
            value: "bookstack"
          - name: MYSQL_PASSWORD
            value: "uglySEA62"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    spec.ingressClassName: traefik
  name: bookstack-ingress
  namespace: default
spec:
  rules:
    - host: bookstack.17042021.xyz
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: bookstack-service
              port:
                number: 80

---
apiVersion: v1
kind: Service
metadata:
  name: bookstack-mysql-svc
  namespace: default
spec:
  type: ClusterIP
  selector:
    bb: mysql
  ports:
    - port: 3306
      targetPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: bookstack-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    bb: bookstack
  ports:
    - port: 80
      targetPort: 80
